name: cenk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80607
title: 'Cenk Sezgin on Technology, Innovation and Learning'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e2dfd8'
    - '#2f2a24'
    - '#50543c'
    - '#bd784d'
  brandStrength: 0.5
  lightness: 0.5866466141305864
  saturation: 0.7962370137684047
  rhythmicContrast: 0.7498471015132964
purpose: []
